### PR TITLE
Shear modulus set to zero if minimum endmember value is 0.

### PR DESCRIPTION
**Pull request by bobmyhill**
Addresses Issue #236

### CODE REVIEW

**Comment by tjhei** [comment]
What if the volume fraction is 0 for the minimum? Shouldn't you still average the other quantities?

**Comment by bobmyhill** [comment]
I guess this is a question of what we want the software to do in unphysical situations. Only fluids have G = 0., and the user should never mix endmembers with undefined and defined Gs. 

Whatever we do, it should be consistent; if we throw an exception for the solid solution if G is not defined, we should do the same for the endmembers. At the moment, I've taken the conservative approach, and just set things to zero (like we currently have for the endmembers).

The alternative approach is to let the Reuss function only throw an exception for a negative argument.

**Comment by tjhei** [comment]
My assumption is that a solid solution of 0% A and 100% B should behave as a B separately, no matter what A is.

**Comment by bobmyhill** [comment]
Yes, that's true. Perhaps it would help if you tell me what you think should happen in the following situations:

1. The user asks for G for an endmember when the EoS doesn't define what it should be (e.g. for the hp_tmt EoS).
2. The user asks for G for a solid solution when none of the endmember EoSs define what G should be.
3. The user asks for G for a solid solution when all the molar fractions are non-zero and one endmember has an EoS with an undefined G.
4. The user asks for G for a solid solution when one endmember has an EoS with an undefined G and that endmember has a volume fraction of zero.

I would suggest that there should be one consistent answer to all of these questions. My preferred answer would be "throw exceptions". The code as it stands (including this PR) favours the alternative "return 0.", which I assume was originally chosen to allow the user to average Vp, Vs, rho simultaneously without worrying about NaNs or exceptions.

**Comment by tjhei** [comment]
Good questions! We also have several places where we produce warnings...

**Comment by bobmyhill** [comment]
So would you just like me to make the warning more verbose?

**Comment by tjhei** [comment]
We could leave the logic as it currently is (warn and return 0), catch the warning in that one test, and call it a day?

**Comment by bobmyhill** [comment]
Yeah, ok, that sounds fine ... do you want to do that?

**Pull request closed without merging**
