### PR TITLE
Changed slb eos volume output from list to float

### PR DESCRIPTION
**Pull request by bobmyhill**

### CODE REVIEW

**Comment by tjhei** [comment]
So this special case is not used in any example or other code right now?

**Comment by bobmyhill** [comment]
It's not a special case, really. I expect burnman to always return a float when I ask it for Cp, S, H, V etc etc.. When the volume query returned a list with a single float a couple of my scripts didn't work (because some of the scipy optimization procedures take a list of floats as input, rather than a list of list of floats). 

I was a little surprised that this didn't show up in any of the tests - perhaps python is more forgiving than I expected.

**Comment by tjhei** [comment]
Well, it is only executed if the brentq can not be applied.

**Comment by tjhei** [comment]
Anyways, thanks for fixing.

**Comment by bobmyhill** [comment]
Ah, I see what you mean. Yes, it is a bit special in that case :)
(I'm dealing a lot with silicate melts (as formulated by de Koker and Stixrude) at the moment, so I'm pushing some of the models to the very limits of their applicable ranges.

Thanks for merging!

**Pull request merged**
