### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by bobmyhill**
Not ready to be merged yet, but opened for comments.

The main changes are as follows:
- Slightly changed the cover page and intro to reflect the changes made this month
- Split the background into several .txt files to facilitate faster editing
- Reordered and added detail to the EoS background
- Added background to solid solution processing
- Added autoclass and autofunction calls for the new thermodynamics functions
- Added many thermodynamics references to ref.bib

### CODE REVIEW

**Comment by ian-r-rose** [comment]
This is starting to look like it is in decent shape.  Can we open a quintilogue on merging?

**Comment by bobmyhill** [comment]
Yes please :)
Timo, Sanne, Cayman ... what do you think?

**Comment by tjhei** [comment]
Looks good. I fixed some sphinx issues.

**Comment by bobmyhill** [comment]
Is this good to go now?

**Comment by ian-r-rose** [comment]
I think so.

**Comment by tjhei** [comment]
Can you explain the reasoning for creating the sphinx/*txt files? Is there a difference between .rst and .txt?

**Comment by bobmyhill** [comment]
The txt files are imported into background.rst ... the suffix absolutely doesn't matter, so we can change them back if you want. What would you suggest?

I broke up background because it was getting far too bulky for me to scan and edit easily.

**Comment by tjhei** [comment]
All other files end with .rst so I was wondering if there was a difference in the way sphinx handles them if they don't end on .rst.

**Comment by bobmyhill** [comment]
No, there's no difference AFAIK. The example given in the sphinx documentation had .txt imports, so I just followed them.

**Pull request merged**
