### PR TITLE
add github actions

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
this seems to be working, @bobmyhill .
One of the tests fails though:
https://github.com/geodynamics/burnman/pull/414/checks?check_run_id=3513587761#step:5:20

**Comment by bobmyhill** [comment]
Thanks @tjhei! This looks great. The broken test was due to sympy changing the format of its nullspace object. A rebase should fix the problem.

**Comment by bobmyhill** [comment]
I've just run the tests with exactly the same package versions, so everything should be updated now. One more rebase should do it!

**Comment by tjhei** [comment]
let's see!

**Comment by bobmyhill** [comment]
Closer! I'm not going to make any wild claims this time, but the next set of deprecated calls have been removed.

**Comment by tjhei** [comment]
Are you pushing directly to master? You could also just add commits here...

**Comment by bobmyhill** [comment]
I was, not best practise, I know. Thankfully the tester now passes. Thanks for doing this!

**Pull request merged**
