### PR TITLE
Updated ipython notebooks

### PR DESCRIPTION
**Pull request by bobmyhill**

### CODE REVIEW

**Comment by ian-r-rose** [comment]
This did not work for me.  Specifically, the new
%matplotlib inline 
commands made it unable to load.

**Comment by bobmyhill** [comment]
Huh. I can't make it work without that line.

**Comment by bobmyhill** [comment]
If you manually remove it, does everything else work?

**Comment by ian-r-rose** [comment]
​The beginner example does, but not the advanced.  In order to get the
inlining working in the old notebooks, I had to launch ipython with

ipython notebook --pylab=inline​

Overall, I am not a huge fan of ipython notebooks.  They always seem so
fussy and easily broken.  Nice for sharing results, but not easy for
development.

**Comment by bobmyhill** [comment]
Ok, this should work now.

**Comment by ian-r-rose** [comment]
Awesome, thanks Bob.

**Pull request merged**
