### PR TITLE
modernizing examples

### PR DESCRIPTION
**Pull request by sannecottaar**
Some examples were broken, and in others I just put a more 'modern' rock. I'm aware that this will probably break a bunch of tests as outputs might have changed, but I don't know how to fix this.

### CODE REVIEW

**Comment by sannecottaar** [comment]
P.s. are we set on 'base_material' in SolidSolution, or could we still name this 'endmembers', since we also have 'n_endmembers'.

**Comment by bobmyhill** [comment]
I would be very happy to call them endmembers. "for endmember in endmembers" is much more sensible than "for endmember in base_material"

**Comment by ian-r-rose** [comment]
I am happy with endmembers.  Someone just has to do it :)

**Comment by bobmyhill** [comment]
I'm happy to do it... give me a few minutes...

**Comment by bobmyhill** [comment]
Ok, pull request opened...

**Comment by ian-r-rose** [comment]
Sanne, this branch is out of date, which is making it tough to run the tests.  Can you rebase it onto master?

**Comment by sannecottaar** [comment]
Done. But I expect a lot of issues with the tests, as a lot of the output
changed.

**Comment by bobmyhill** [comment]
Do you want me to check/change the test output, or are you happy to do this? It's pretty simple ... all the comparison files are in misc/ref - they need changing after checking that nothing has gone wrong...

**Comment by ian-r-rose** [comment]
The tester just checks the output of the script against some reference previous output in misc/ref.  In order to update the output, all you need to do is copy the new output into that folder, with the appropriate name.

**Comment by sannecottaar** [comment]
Yes, that looks doable. If it wasn't that the test suite is now already
failing at test_partitioning.py, which I think should not have changed.

**Comment by ian-r-rose** [comment]
I think the test_partitioning.py failure is in your other open PR.  This one looks fine to me.

**Comment by ian-r-rose** [comment]
Sanne, what is the status of this?  Is there a merge commit for the base_materials->endmembers change here?

**Comment by sannecottaar** [comment]
Ok, I changed some of the output files for the examples. I don't know why the comparison with master shows all the base_materials to endmembers changes, since that came from merging with master.

I do find the testing of the examples a bit random. Do we really want this? The original output to screen is a bit random in the first place. I was able to change some examples without breaking them. On the other hand example_composition.py will be broken if one of the other (True/False)-options gets chosen.

**Comment by bobmyhill** [comment]
"I don't know why the comparison with master shows all the base_materials to endmembers changes, since that came from merging with master."

That's a "feature" of merging. I think that in general *git rebase -i* master is much cleaner than git merge.
As the merge wasn't a separate commit, we can't undo it easily.

Timo and I discussed the example tests in Berkeley - they are obviously not thorough tests of the examples, but they do help to identify when we've done something badly wrong.

**Comment by sannecottaar** [comment]
Yeah, I guess it does show when errors are popping up.
I will try 'git rebase -i master' next time.

**Comment by tjhei** [comment]
if you rebase to master now all the ```base_materials``` to ```endmembers``` changes should go away.

**Comment by sannecottaar** [comment]
It claims it is up to date.

**Comment by tjhei** [comment]
Nope. Switch to master and update it first:
```
   git checkout master
   git pull --ff-only upstream
   git checkout update_examples
   git rebase master
```

**Comment by bobmyhill** [comment]
Hmmm, test_partitioning is rather opaque to me. I tried to check your old and new a and b values using eq. 6 from Nakajima et al., 2012, and neither of them agree with my calculations. It might be a problem with my calculations, though...

Are a and b  X_per_FeO/X_per_MgO and X_pv_FeSiO3/X_pv_MgSiO3 respectively?



The additional imports for test_partitioning.py are
import numpy as np
import burnman.constants

The check lines I added were these ones, which should sum to zero:
        a = 0.0319126180713
        b = 0.125395826369
        X_per_FeO = a/(a+1)
        X_pv_FeSiO3 = b/(b+1)
        print burnman.constants.gas_constant*temperature*np.log((X_pv_FeSiO3 / (1-X_pv_FeSiO3)) / (X_per_FeO/(1.-X_per_FeO))) - (-22300. - 200.*(pressure/1.e9) - 4.0*temperature + 4900.*(1. - 2.*X_pv_FeSiO3) + (11000. + 110.*(pressure/1.e9))*(1. - 2.*X_per_FeO))

**Comment by ian-r-rose** [comment]
I think this particular test should be on the chopping block. That being said, it should not be broken by these PRs.

**Comment by bobmyhill** [comment]
We definitely need a test for the functions in partitioning.py though, especially as I can't reproduce the values...

**Comment by sannecottaar** [comment]
The problem with the partitioning example is only in fix_prem. As far as
I'm aware, this one can be merged.

**Comment by tjhei** [comment]
tests pass here

**Comment by bobmyhill** [comment]
Can you remove the stray floats in the mineral definitions? I don't think they do anything.
e.g. minerals.SLB_2005.mg_fe_perovskite(0.7) -> minerals.SLB_2005.mg_fe_perovskite()

On a related note, I was considering modifying solid solution instances to allow lists of floats to set_composition on init, like this:
pv_composition=[0.9,0.1,0.0]
pv=minerals.SLB_2005.mg_fe_perovskite(pv_composition)

Not for this pull request, of course, but what do you think?

**Comment by bobmyhill** [comment]
There are some more stray fe_nums in 
* examples/example_geotherms.py and  
* examples/example_woutput.py

**Comment by sannecottaar** [comment]
I think I have already removed those. At the moment the fe_num still seem
correct for the 2005 database. Should we change that? I updated the
examples to the 2011 database, and included set_composition statements. I
agree, including set_composition in init is nice.

**Comment by bobmyhill** [comment]
Ah, yes, I was forgetting the differences with the 2005 database. Eventually we can change it to be completely consistent with the 2011 database, but that's not for this PR, I think.

Are you happy with this one now? If so, I'll merge.

**Comment by sannecottaar** [comment]
Yep.

**Pull request merged**
