### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by bobmyhill**
Not to be merged yet, I'm working on it!

### CODE REVIEW

**Comment by bobmyhill** [comment]
This should help #154 go away...

**Comment by tjhei** [comment]
What is the status of this @bobmyhill ? Is there a reason you are using .txt instead of .rst files?

**Comment by tjhei** [comment]
I am also not too happy with you killing our pretty flow picture and replace it with something completely unstructured. I guess we can now do more things than before, but there is still a flow of data in some way, right?

**Comment by bobmyhill** [comment]
The txt files are not new. We discussed them some time ago, when the original thermo rst file got quite big.

**Comment by bobmyhill** [comment]
For me, no, there isn't really any set flow, and the original diagram doesn't cover any of my additions. 

One solution could be three or four similar diagrams describing a few possible workflows (of which the original would be one).

**Comment by bobmyhill** [comment]
Here are a few suggested workflows:
* Make model -> Fit experimental data -> Model uncertainties
* Mineral models -> P-Ts -> equilibrium phase relations (mostly manual at the moment)
* Predict/compare seismic velocities (your example, kinda requires the previous to be automated, which isn't yet done because none of us know how/want to put the effort in)
* Build a planet

**Comment by tjhei** [comment]
I like the idea of showing several example workflows. Here is how we could generate them using dot inside sphinx. Does anybody want to play with this?
```
.. graphviz::

   digraph foo {
      rankdir=LR;
   subgraph cluster_1 {
      label=" bla bla";
      "Geotherm" -> "bla";
      "minerals" -> "bla";
      "bla" -> " something else";
   }
   subgraph cluster_2 {
      label="a b c";
      a [label="sphinx", href="http://sphinx-doc.org", target="_top"];
      a -> "baz" [label="blabla"]; 
      baz -> c;
      d -> c;
   }
   }
```
gives: 
graphviz-d73437753a9848bdbaaebe64fa62e22a9d135545

**Comment by bobmyhill** [comment]
Ooooh, me likey. Yes, I'm happy to look at doing this.

Bob

**Comment by bobmyhill** [comment]
Ok, what do you think of this?

**Comment by bobmyhill** [comment]
@tjhei (the flow diagram, not all of the updates...)

**Comment by tjhei** [comment]
can you drop the .png in here so I don't have to compile?

**Comment by bobmyhill** [comment]
workflow

**Comment by bobmyhill** [comment]
I don't know whether there's a standard symbol for classes and functions...

**Comment by tjhei** [comment]
Neat. That is a good start.

**Comment by lordkman** [comment]
Whoa... This is awesome Bob! Great work

**Pull request closed without merging**
