### PR TITLE
Evaluate now takes an n dimensional list of pressures and temperatures

### PR DESCRIPTION
**Pull request by bobmyhill**
Useful when using np.meshgrid to create a grid of properties.

### CODE REVIEW

**Comment by tjhei** [comment]
I am not sure I understand, you want to allow any shape for the input and then return the output in the same shape? Not sure if this is a great idea. We would need to at least check that the shapes of p and T are compatible.

**Comment by sannecottaar** [comment]
Seems reasonable to do a grid at once. I think we always needed to put the same shape in (couldn't calculate a range of temperatures at one pressure). Check would be useful.

**Comment by tjhei** [comment]
I am fine with this, provided:
1. we assert that the shapes you put in are compatible
2. you add unit tests that check that if you put in a list, a 1d array, and a 2d array and verify that the output shape is correct.

**Comment by bobmyhill** [comment]
Not sure why this is failing ... perplex.py isn't even in this PR

**Comment by bobmyhill** [comment]
Ok, all fixed.

**Comment by tjhei** [comment]
great!

**Pull request merged**
