### PR TITLE
new forum: change on homepage and readme

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
I realized we never advertised the google group, it is mostly unused. Sanne and I discussed the move to the CIG forums. I hope everybody is happy with this...

**Comment by bobmyhill** [comment]
Hi @tjhei ... we seem to be lacking sympy on the test machine again...

**Comment by tjhei** [comment]
> we seem to be lacking sympy on the test machine again...

no, this is the old tester that I haven't turned off apparently.

**Comment by bobmyhill** [comment]
Ok, looks good to me.

**Pull request merged**
