### PR TITLE
changelog

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
anything else I am missing?

**Comment by tjhei** [comment]
anything else I am missing?

**Comment by sannecottaar** [comment]
- many more mineral physical parameter databases
- tutorial

**Comment by tjhei** [comment]
added

**Comment by bobmyhill** [comment]
- Added interface for property modifications
- Added ideal, symmetric, asymmetric and subregular solution model formulations

**Comment by sannecottaar** [comment]
We should be good to go right? Whenever you have time,Timo.

**Comment by tjhei** [comment]
Really busy right now. I am in Cambridge next week, though. :-)

**Comment by sannecottaar** [comment]
Next week, already? Shit, I won't be :( I'll be in China until May 2nd.
Sorry!

**Pull request merged**
