### PR TITLE
Improve dataset accuracy

### PR DESCRIPTION
**Pull request by bobmyhill**
The values in Stixrude and Lithgow-Bertelloni are reported only to the number of significant figures for which they are confident. Annoyingly, this is not the number of significant figures required to reproduce the figures in their paper. This pull request fixes SLB_2011.py and adds appropriate tests, resolving Issue #230.

### CODE REVIEW

**Comment by sannecottaar** [comment]
Wow, thanks for this!

**Comment by lordkman** [comment]
Good catch Bob!

**Comment by bobmyhill** [comment]
I also added an entropy term (via the new modify_properties interface) to a few SLB phases, which Stixrude and Lithgow-Bertelloni included (perhaps a bit obscurely in the paper) to account for magnetic/configurational entropy. This entropy term is unphysical at low temperatures (when phases are completely ordered and S should be zero).

**Comment by bobmyhill** [comment]
Also also, if you were wondering why I've been banging on about approaching gibbs minimization from an equilibrium perspective, see the new benchmark in /misc/benchmarks/olivine_phase_diagram_benchmark.py ... it's much quicker than gridded minimization.

**Comment by bobmyhill** [comment]
Ok, I see happy green lights!

**Comment by tjhei** [comment]
What is the license for stx11ver.dat? I am not sure we can include it with the code...

**Comment by bobmyhill** [comment]
stx11ver.dat is sourced from the Perple_X datasets directory; Perple_X doesn't have a licence.

I think it's fine to include here, but if you would rather it were removed, then I can just leave a readme...

**Comment by tjhei** [comment]
> I think it's fine to include here

Do you have the right to license it under GPL2+? I don't think so. I would feel better if we don't include it. If I understand it correctly, you have added a script that loads it in an writes a mineral file we use? So, everything works without that file?

**Comment by bobmyhill** [comment]
Good point; ok, I'm happy to remove it and leave a little note in the conversion file saying that the file is required, and from where it can be downloaded.

**Comment by sannecottaar** [comment]
Why do we include the inversion file? I didn't include the ones that put
the seismic data in a consistent format.

**Comment by bobmyhill** [comment]
There's also tc-ds62.txt in there, which also doesn't belong to us... I guess we should remove that too.

I like having the conversion files there for when new versions of the datasets are released (or for users to input their old copies of the datasets). If you think they should be removed, we can definitely do that, but then I take on the job of "Keeper of the dataset conversion scripts", and I don't like that idea.

**Comment by tjhei** [comment]
> I like having the conversion files there

Agreed.

**Comment by bobmyhill** [comment]
Ok, I've deleted the offending datasets, but added notes to the python scripts telling the user where to go to get the necessary files.

**Comment by tjhei** [comment]
Thanks. We would need to squash the commits, otherwise the file will be in the history.

What are the  burnman/data/input_perplex/*dat files for?

**Comment by bobmyhill** [comment]
I'm happy to squash the commits if you want, but it won't help... the HP dataset has been in burnman for over a year. Would you still prefer this PR squished?

The input_perplex files contain inputs to mineral benchmarks; they are snippets of code output from perplex. They're just tables of properties at given P and T.

**Comment by tjhei** [comment]
Alright, looks good to me. Does anybody else have any comments?

**Comment by sannecottaar** [comment]
Nope. Looks great!

**Pull request merged**
