### PR TITLE
[RFC] PEP8 fixes for Burnman

### PR DESCRIPTION
**Pull request by souravsingh**
Made some PEP8 fixes for some scripts in the project.

### CODE REVIEW

**Comment by souravsingh** [comment]
This is related to Issue #157

**Comment by tjhei** [comment]
Thanks for this contribution. We are in the process of merging several other branches for the next release first (to avoid conflicts) and we are planning to do the pep fixes after that.

**Comment by souravsingh** [comment]
Oh, I am sorry to send the PR really early

**Comment by tjhei** [comment]
Thanks again. fixed in #244

**Pull request closed without merging**
