### PR TITLE
remove .error files generated from test.sh

### PR DESCRIPTION
**Pull request by tjhei**
addresses #240

### CODE REVIEW

**Comment by tjhei** [comment]
updated.

**Comment by bobmyhill** [comment]
Ok, great! Do you want to do something with uncertainty.dat?

**Comment by tjhei** [comment]
I don't really like to make the tutorial more complicated. I now added the file to .gitignore. Acceptable?

**Comment by tjhei** [comment]
wait with merging.

**Comment by bobmyhill** [comment]
Is the output even necessary? Could the output just be suppressed?

**Comment by tjhei** [comment]
step_3 writes the files and reads it in again when you want to plot. Of course we could add some magic that skips writing the file when we run the tests, but as I said, I think this is somewhat ugly for a tutorial.

**Comment by tjhei** [comment]
I had to mess with the sed line even further because it stopped working on linux. Can you give the current version a try on mac os?

**Comment by bobmyhill** [comment]
Yup, that's what I was suggesting before... It's the sed recommended style, so it should work in all systems. Ready to go?

**Comment by tjhei** [comment]
working correctly under linux, so yes if it works for you.

**Pull request merged**
