### PR TITLE
Add texlive to bionic buildenvs

### PR DESCRIPTION
**Pull request by tjesser-ucdavis-edu**

### CODE REVIEW

**Comment by bobmyhill** [comment]
@tjesser-ucdavis-edu jenkins still isn't happy, bless 'im.

**Comment by tjesser-ucdavis-edu** [comment]
Jenkins uses the Docker containers on DockerHub and DockerHub is only set up to build the Dockerfiles in master. Since this pull request is for changing the buildenv container, the Jenkins builder won't reflect the change.

It's not a great dependency chain, but the build environment shouldn't change as much as other parts of the project.

Only other solution I can think of would be to make the package installation part of the build process, but that would mean downloading and installing packages for every PR.

**Comment by bobmyhill** [comment]
Ah, I see. Thanks for the explanation!

**Pull request merged**
